-- +goose Up
-- +goose StatementBegin
CREATE TABLE project (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  type text NOT NULL,
  user_id bigint NOT NULL REFERENCES user_ ON DELETE CASCADE,
  visibility text NOT NULL,
  name text NOT NULL,
  data jsonb NOT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE project;
-- +goose StatementEnd
