-- +goose Up
-- +goose StatementBegin
CREATE EXTENSION citext;
CREATE TABLE user_ (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  username citext NOT NULL UNIQUE,
  email citext NOT NULL UNIQUE,
  password_hash text NOT NULL,
  role TEXT NOT NULL DEFAULT 'USER',
  display_name text NOT NULL DEFAULT '',
  about text NOT NULL DEFAULT ''
);
INSERT INTO user_ (
  username, email, password_hash
) VALUES (
  'ghost', '', ''
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE user_;
DROP EXTENSION citext;
-- +goose StatementEnd
